config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :credits
  resources :semesters
  devise_for :users
  devise_for :docentes
  resources :teachers
  resources :schools
  resources :schedules
  resources :subjects
  resources :notes
  resources :programs
 
#declarar rutas	
  get 'bienvenido/index'
  get 'bienvenido/monitorias'
  get 'bienvenido/cursos'
  get 'bienvenido/nosotros'
  get 'bienvenido/contactenos'
  get 'bienvenido/Entrar_cursos'
  get 'bienvenido/monitorias_usuario'
#empezar localhost
  root 'bienvenido#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/credit.rb
class Credit < ApplicationRecord
	has_many :subjects
	def to_s
	numero
end
end

app/models/docente.rb
class Docente < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :teacher       
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :semester
  has_many :subjects
  
end

app/models/program.rb
class Program < ApplicationRecord
  belongs_to :school
  has_many :subjects
  def to_s
	nombre
end
end

app/models/schedule.rb
class Schedule < ApplicationRecord
	has_many :students
	has_many :teachers
	has_many :subjects
def to_s
	hora_inicio
		
end	
	def self.ingresarMonitoria(student_id, subject_id)
		subject = Subject.find_by(codigo: subject_id)
		subject.student_id = id_student
		if subject.save
			return "Monitoria asignada correctamente"
		else
			return subject.errors.inspect + " " + "La monitoria no se ha asignado correctamente. Intente mas tarde o contacte con soporte"
		end
	end
	
end

app/models/school.rb
class School < ApplicationRecord
	has_many :teachers
	has_many :programs
	has_many :students
	def to_s
		nombre
	end	
end

app/models/semester.rb
class Semester < ApplicationRecord
	has_many :students
	has_many :notes
def to_s
	numero
end
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :Schedule
  belongs_to :User
  belongs_to :School
  belongs_to :Semester
  def self.calcPromedio(id_student)
		student = Student.find(id_student)
		#EL ESTUDIANTE TIENE UN PROMEDIO DE MAS DE 3.8 Y ES ESTUDIATE?
		if student.promedio >= 3.8 and student.tipo_estudiante == 0
			return true
		#EL ESTUDIANTE TIENE UN PROMEDIO DE MAS DE 4.2 Y ES EGRESADO?
		elsif student.promedio >= 4.2 and student.tipo_estudiante == 1
			return true
		else
			return false
		end
	end
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :credit
  belongs_to :note
  belongs_to :program
  belongs_to :schedule
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :school
  belongs_to :schedule
  belong_to :docente
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, presence: true        
  has_one :student,dependent: :destroy
  def to_s
  	email
  end
    
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:dia, :hora_inicio, :hora_fin)
    end
end

app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/schedules/_form.html.erb
<%= form_with(model: schedule, local: true) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dia %>
    <%= form.text_field :dia, id: :schedule_dia %>
  </div>

  <div class="field">
    <%= form.label :hora_inicio %>
    <%= form.time_select :hora_inicio, id: :schedule_hora_inicio %>
  </div>

  <div class="field">
    <%= form.label :hora_fin %>
    <%= form.time_select :hora_fin, id: :schedule_hora_fin %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<p id="notice"><%= notice %></p>
<%= stylesheet_link_tag 'estudiante/estilo_moniusuario' , :media => "all" %>
<header class="header">
  <div class="contenedor" >
      <img class="logo"  src="<%= asset_path 'logo.jpg' %>"  width="400px" height="80px">
      <span class="icon-menu" id="btn-menu"></span>
      <nav class="nav" id="nav">
      <ul class="menu">
      <li class="menu-item"><a class="menu_link select"  href="../bienvenido/index.html">Inicio</a></li>
      <li class="menu-item"><a class="menu_link" href="../bienvenido/monitorias.html">Monitorias</a>
      <li class="menu-item"><a class="menu_link" href="../bienvenido/nosotros.html">Estudia Con Nosotros</a></li>
      <li class="menu-item"><a class="menu_link" href="../bienvenido/cursos.html">Cursos</a></li>
      <li class="menu-item"><a class="menu_link" href="../bienvenido/contactenos.html">Contactenos</a></li>
    </ul>
    </nav>
    </div>
    </header>
<h1>Schedules</h1>

<table>
  <thead>
    <tr class="columna1">
      <th>Dia</th>
      <th>Hora inicio</th>
      <th>Hora fin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr class="columna2">
        <td><%= schedule.dia %></td>
        <td><%= schedule.hora_inicio %></td>
        <td><%= schedule.hora_fin %></td>
     
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dia:</strong>
  <%= @schedule.dia %>
</p>

<p>
  <strong>Hora inicio:</strong>
  <%= @schedule.hora_inicio %>
</p>

<p>
  <strong>Hora fin:</strong>
  <%= @schedule.hora_fin %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>