config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :credits
  resources :semesters
  devise_for :users
  devise_for :docentes
  resources :teachers
  resources :schools
  resources :schedules
  resources :subjects
  resources :notes
  resources :programs
 
#declarar rutas	
  get 'bienvenido/index'
  get 'bienvenido/monitorias'
  get 'bienvenido/cursos'
  get 'bienvenido/nosotros'
  get 'bienvenido/contactenos'
  get 'bienvenido/Entrar_cursos'
  get 'bienvenido/monitorias_usuario'
#empezar localhost
  root 'bienvenido#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/credit.rb
class Credit < ApplicationRecord
	has_many :subjects
	def to_s
	numero
end
end

app/models/docente.rb
class Docente < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :teacher       
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :semester
  has_many :subjects
  
end

app/models/program.rb
class Program < ApplicationRecord
  belongs_to :school
  has_many :subjects
  def to_s
	nombre
end
end

app/models/schedule.rb
class Schedule < ApplicationRecord
	has_many :students
	has_many :teachers
	has_many :subjects
def to_s
	hora_inicio
		
end	
	def self.ingresarMonitoria(student_id, subject_id)
		subject = Subject.find_by(codigo: subject_id)
		subject.student_id = id_student
		if subject.save
			return "Monitoria asignada correctamente"
		else
			return subject.errors.inspect + " " + "La monitoria no se ha asignado correctamente. Intente mas tarde o contacte con soporte"
		end
	end
	
end

app/models/school.rb
class School < ApplicationRecord
	has_many :teachers
	has_many :programs
	has_many :students
	def to_s
		nombre
	end	
end

app/models/semester.rb
class Semester < ApplicationRecord
	has_many :students
	has_many :notes
def to_s
	numero
end
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :Schedule
  belongs_to :User
  belongs_to :School
  belongs_to :Semester
  def self.calcPromedio(id_student)
		student = Student.find(id_student)
		#EL ESTUDIANTE TIENE UN PROMEDIO DE MAS DE 3.8 Y ES ESTUDIATE?
		if student.promedio >= 3.8 and student.tipo_estudiante == 0
			return true
		#EL ESTUDIANTE TIENE UN PROMEDIO DE MAS DE 4.2 Y ES EGRESADO?
		elsif student.promedio >= 4.2 and student.tipo_estudiante == 1
			return true
		else
			return false
		end
	end
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :credit
  belongs_to :note
  belongs_to :program
  belongs_to :schedule
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :school
  belongs_to :schedule
  belong_to :docente
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, presence: true        
  has_one :student,dependent: :destroy
  def to_s
  	email
  end
    
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  before_action :set_credit, only: [:show, :edit, :update, :destroy]

  # GET /credits
  # GET /credits.json
  def index
    @credits = Credit.all
  end

  # GET /credits/1
  # GET /credits/1.json
  def show
  end

  # GET /credits/new
  def new
    @credit = Credit.new
  end

  # GET /credits/1/edit
  def edit
  end

  # POST /credits
  # POST /credits.json
  def create
    @credit = Credit.new(credit_params)

    respond_to do |format|
      if @credit.save
        format.html { redirect_to @credit, notice: 'Credit was successfully created.' }
        format.json { render :show, status: :created, location: @credit }
      else
        format.html { render :new }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credits/1
  # PATCH/PUT /credits/1.json
  def update
    respond_to do |format|
      if @credit.update(credit_params)
        format.html { redirect_to @credit, notice: 'Credit was successfully updated.' }
        format.json { render :show, status: :ok, location: @credit }
      else
        format.html { render :edit }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credits/1
  # DELETE /credits/1.json
  def destroy
    @credit.destroy
    respond_to do |format|
      format.html { redirect_to credits_url, notice: 'Credit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit
      @credit = Credit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credit_params
      params.require(:credit).permit(:numero)
    end
end

app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/credits/_form.html.erb
<%= form_with(model: credit, local: true) do |form| %>
  <% if credit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(credit.errors.count, "error") %> prohibited this credit from being saved:</h2>

      <ul>
      <% credit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :numero %>
    <%= form.number_field :numero, id: :credit_numero %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/credits/edit.html.erb
<h1>Editing Credit</h1>

<%= render 'form', credit: @credit %>

<%= link_to 'Show', @credit %> |
<%= link_to 'Back', credits_path %>

app/views/credits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Credits</h1>

<table>
  <thead>
    <tr>
      <th>Numero</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @credits.each do |credit| %>
      <tr>
        <td><%= credit.numero %></td>
        <td><%= link_to 'Show', credit %></td>
        <td><%= link_to 'Edit', edit_credit_path(credit) %></td>
        <td><%= link_to 'Destroy', credit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Credit', new_credit_path %>

app/views/credits/new.html.erb
<h1>New Credit</h1>

<%= render 'form', credit: @credit %>

<%= link_to 'Back', credits_path %>

app/views/credits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero:</strong>
  <%= @credit.numero %>
</p>

<%= link_to 'Edit', edit_credit_path(@credit) %> |
<%= link_to 'Back', credits_path %>