config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :credits
  resources :semesters
  devise_for :users
  devise_for :docentes
  resources :teachers
  resources :schools
  resources :schedules
  resources :subjects
  resources :notes
  resources :programs
 
#declarar rutas	
  get 'bienvenido/index'
  get 'bienvenido/monitorias'
  get 'bienvenido/cursos'
  get 'bienvenido/nosotros'
  get 'bienvenido/contactenos'
  get 'bienvenido/Entrar_cursos'
  get 'bienvenido/monitorias_usuario'
#empezar localhost
  root 'bienvenido#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/credit.rb
class Credit < ApplicationRecord
	has_many :subjects
	def to_s
	numero
end
end

app/models/docente.rb
class Docente < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :teacher       
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :semester
  has_many :subjects
  
end

app/models/program.rb
class Program < ApplicationRecord
  belongs_to :school
  has_many :subjects
  def to_s
	nombre
end
end

app/models/schedule.rb
class Schedule < ApplicationRecord
	has_many :students
	has_many :teachers
	has_many :subjects
def to_s
	hora_inicio
		
end	
	def self.ingresarMonitoria(student_id, subject_id)
		subject = Subject.find_by(codigo: subject_id)
		subject.student_id = id_student
		if subject.save
			return "Monitoria asignada correctamente"
		else
			return subject.errors.inspect + " " + "La monitoria no se ha asignado correctamente. Intente mas tarde o contacte con soporte"
		end
	end
	
end

app/models/school.rb
class School < ApplicationRecord
	has_many :teachers
	has_many :programs
	has_many :students
	def to_s
		nombre
	end	
end

app/models/semester.rb
class Semester < ApplicationRecord
	has_many :students
	has_many :notes
def to_s
	numero
end
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :Schedule
  belongs_to :User
  belongs_to :School
  belongs_to :Semester
  def self.calcPromedio(id_student)
		student = Student.find(id_student)
		#EL ESTUDIANTE TIENE UN PROMEDIO DE MAS DE 3.8 Y ES ESTUDIATE?
		if student.promedio >= 3.8 and student.tipo_estudiante == 0
			return true
		#EL ESTUDIANTE TIENE UN PROMEDIO DE MAS DE 4.2 Y ES EGRESADO?
		elsif student.promedio >= 4.2 and student.tipo_estudiante == 1
			return true
		else
			return false
		end
	end
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :credit
  belongs_to :note
  belongs_to :program
  belongs_to :schedule
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :school
  belongs_to :schedule
  belong_to :docente
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, presence: true        
  has_one :student,dependent: :destroy
  def to_s
  	email
  end
    
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:codigo, :nombre, :apellido, :school_id, :schedule_id)
    end
end

app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher, local: true) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :codigo %>
    <%= form.number_field :codigo, id: :teacher_codigo %>
  </div>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :teacher_nombre %>
  </div>

  <div class="field">
    <%= form.label :apellido %>
    <%= form.text_field :apellido, id: :teacher_apellido %>
  </div>

  <div class="field">
    <%= form.label :school_id %>
    <%= form.text_field :school_id, id: :teacher_school_id %>
  </div>

  <div class="field">
    <%= form.label :schedule_id %>
    <%= form.text_field :schedule_id, id: :teacher_schedule_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>
<%= stylesheet_link_tag 'estudiante/estilo_moniusuario' , :media => "all" %>
<header class="header">
  <div class="contenedor" >
      <img class="logo"  src="<%= asset_path 'logo.jpg' %>"  width="400px" height="80px">
      <span class="icon-menu" id="btn-menu"></span>
      <nav class="nav" id="nav">
      <ul class="menu">
      <li class="menu-item"><a class="menu_link select"  href="../bienvenido/index.html">Inicio</a></li>
      <li class="menu-item"><a class="menu_link" href="../bienvenido/monitorias.html">Monitorias</a>
      <li class="menu-item"><a class="menu_link" href="../bienvenido/nosotros.html">Estudia Con Nosotros</a></li>
      <li class="menu-item"><a class="menu_link" href="../bienvenido/cursos.html">Cursos</a></li>
      <li class="menu-item"><a class="menu_link" href="../bienvenido/contactenos.html">Contactenos</a></li>
    </ul>
    </nav>
    </div>
    </header>
<h1>Teachers</h1>

<table>
  <thead>
    <tr>
      <th>Codigo</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>School</th>
      <th>Schedule</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.codigo %></td>
        <td><%= teacher.nombre %></td>
        <td><%= teacher.apellido %></td>
        <td><%= teacher.school %></td>
        <td><%= teacher.schedule %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @teacher.codigo %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @teacher.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @teacher.apellido %>
</p>

<p>
  <strong>School:</strong>
  <%= @teacher.school %>
</p>

<p>
  <strong>Schedule:</strong>
  <%= @teacher.schedule %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>